"""
Comprehensive list of Toronto community centers with indoor swimming pools.
This data is compiled from Toronto Parks, Forestry & Recreation facilities.
"""

TORONTO_INDOOR_POOLS = [
    # Downtown Core
    {
        "name": "Regent Park Aquatic Centre",
        "address": "402 Shuter St, Toronto, ON M5A 1X1",
        "postal_code": "M5A 1X1",
        "district": "Toronto Centre",
        "latitude": 43.6604,
        "longitude": -79.3669,
        "phone": "416-392-0740",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/176/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Toronto Pan Am Sports Centre",
        "address": "875 Morningside Ave, Toronto, ON M1C 0C7",
        "postal_code": "M1C 0C7",
        "district": "Scarborough",
        "latitude": 43.7858,
        "longitude": -79.1851,
        "phone": "416-287-7765",
        "website": "https://www.tpasc.ca",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Scarborough Civic Centre Aquatic Complex",
        "address": "150 Borough Dr, Toronto, ON M1P 4N7",
        "postal_code": "M1P 4N7",
        "district": "Scarborough",
        "latitude": 43.7739,
        "longitude": -79.2582,
        "phone": "416-396-4039",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/270/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    
    # North York
    {
        "name": "North York YMCA",
        "address": "20 Avondale Ave, Toronto, ON M2N 2S1",
        "postal_code": "M2N 2S1",
        "district": "North York",
        "latitude": 43.7567,
        "longitude": -79.4109,
        "phone": "416-250-0200",
        "website": "https://ymcagta.org/find-a-y/north-york-ymca",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Giovanni Caboto Community Centre",
        "address": "1550 Bathurst St, Toronto, ON M5P 3H8",
        "postal_code": "M5P 3H8",
        "district": "Toronto Centre",
        "latitude": 43.7123,
        "longitude": -79.4169,
        "phone": "416-392-0744",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/283/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Grandravine Community Recreation Centre",
        "address": "23 Grandravine Dr, Toronto, ON M3N 1H3",
        "postal_code": "M3N 1H3",
        "district": "North York",
        "latitude": 43.7294,
        "longitude": -79.5036,
        "phone": "416-395-6040",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/280/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Fairview Community Pool",
        "address": "1803 Sheppard Ave E, Toronto, ON M2J 5B1",
        "postal_code": "M2J 5B1",
        "district": "North York",
        "latitude": 43.7771,
        "longitude": -79.3477,
        "phone": "416-395-6040",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/150/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    
    # Etobicoke
    {
        "name": "Etobicoke Olympium",
        "address": "590 Rathburn Rd, Etobicoke, ON M9C 3T3",
        "postal_code": "M9C 3T3",
        "district": "Etobicoke",
        "latitude": 43.6448,
        "longitude": -79.5577,
        "phone": "416-394-8754",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/152/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Burnhamthorpe Community Centre",
        "address": "20 Winterton Dr, Etobicoke, ON M9B 3P2",
        "postal_code": "M9B 3P2",
        "district": "Etobicoke",
        "latitude": 43.6517,
        "longitude": -79.5788,
        "phone": "416-394-8840",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/132/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "York Recreation Centre",
        "address": "22 Guestville Ave, Toronto, ON M8W 4E9",
        "postal_code": "M8W 4E9",
        "district": "Etobicoke",
        "latitude": 43.6048,
        "longitude": -79.5201,
        "phone": "416-392-7145",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/233/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Westway Community Centre",
        "address": "40 Hawksbury Dr, Etobicoke, ON M9V 4M4",
        "postal_code": "M9V 4M4",
        "district": "Etobicoke",
        "latitude": 43.7384,
        "longitude": -79.5820,
        "phone": "416-394-8840",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/159/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    
    # Scarborough
    {
        "name": "McGregor Park Community Centre",
        "address": "2231 Lawrence Ave E, Toronto, ON M1P 2P7",
        "postal_code": "M1P 2P7",
        "district": "Scarborough",
        "latitude": 43.7554,
        "longitude": -79.2741,
        "phone": "416-396-4046",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/138/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "L'Amoreaux Recreation Centre",
        "address": "2000 McNicoll Ave, Toronto, ON M1V 5L7",
        "postal_code": "M1V 5L7",
        "district": "Scarborough",
        "latitude": 43.8049,
        "longitude": -79.2943,
        "phone": "416-396-4046",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/123/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Malvern Recreation Centre",
        "address": "30 Sewells Rd, Toronto, ON M1B 3G5",
        "postal_code": "M1B 3G5",
        "district": "Scarborough",
        "latitude": 43.8078,
        "longitude": -79.2247,
        "phone": "416-396-4046",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/139/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Albert Campbell District Park Pool",
        "address": "496 Birchmount Rd, Toronto, ON M1K 1M9",
        "postal_code": "M1K 1M9",
        "district": "Scarborough",
        "latitude": 43.7293,
        "longitude": -79.2655,
        "phone": "416-396-4046",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/149/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    
    # East York
    {
        "name": "Stan Wadlow Clubhouse",
        "address": "373 Cedarvale Ave, Toronto, ON M4C 4K7",
        "postal_code": "M4C 4K7",
        "district": "East York",
        "latitude": 43.6953,
        "longitude": -79.3063,
        "phone": "416-392-0751",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/146/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Jimmie Simpson Recreation Centre",
        "address": "870 Queen St E, Toronto, ON M4M 1J3",
        "postal_code": "M4M 1J3",
        "district": "Toronto East",
        "latitude": 43.6595,
        "longitude": -79.3459,
        "phone": "416-392-0751",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/219/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    
    # Central Toronto
    {
        "name": "Miles Nadal JCC",
        "address": "750 Spadina Ave, Toronto, ON M5S 2J2",
        "postal_code": "M5S 2J2",
        "district": "Toronto Centre",
        "latitude": 43.6635,
        "longitude": -79.4055,
        "phone": "416-924-6211",
        "website": "https://mnjcc.org",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Toronto Athletic Club",
        "address": "1 Shoreham Dr, Toronto, ON M3N 1S4",
        "postal_code": "M3N 1S4",
        "district": "North York",
        "latitude": 43.7289,
        "longitude": -79.4754,
        "phone": "416-630-9000",
        "website": "https://www.tac.com",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Wallace Emerson Community Centre",
        "address": "1260 Dufferin St, Toronto, ON M6H 4C3",
        "postal_code": "M6H 4C3",
        "district": "Toronto Centre",
        "latitude": 43.6677,
        "longitude": -79.4343,
        "phone": "416-392-0743",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/277/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "High Park Pool",
        "address": "375 Colborne Lodge Dr, Toronto, ON M6R 2Z3",
        "postal_code": "M6R 2Z3",
        "district": "Toronto West",
        "latitude": 43.6465,
        "longitude": -79.4673,
        "phone": "416-392-1111",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/155/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    
    # Additional Community Centers
    {
        "name": "Oriole Community Centre",
        "address": "2975 Don Mills Rd W, Toronto, ON M2J 3B7",
        "postal_code": "M2J 3B7",
        "district": "North York",
        "latitude": 43.7773,
        "longitude": -79.3507,
        "phone": "416-395-6040",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/151/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Albion Neighbourhood Services",
        "address": "1530 Albion Rd, Etobicoke, ON M9V 1B4",
        "postal_code": "M9V 1B4",
        "district": "Etobicoke",
        "latitude": 43.7367,
        "longitude": -79.5622,
        "phone": "416-394-8840",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/281/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Moss Park Arena and Recreation Centre",
        "address": "140 Sherbourne St, Toronto, ON M5A 2R2",
        "postal_code": "M5A 2R2",
        "district": "Toronto Centre",
        "latitude": 43.6562,
        "longitude": -79.3698,
        "phone": "416-392-0744",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/167/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Matty Eckler Recreation Centre",
        "address": "953 Gerrard St E, Toronto, ON M4M 1Z4",
        "postal_code": "M4M 1Z4",
        "district": "Toronto East",
        "latitude": 43.6663,
        "longitude": -79.3386,
        "phone": "416-392-0751",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/147/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Leaside Memorial Community Gardens",
        "address": "1073 Millwood Rd, Toronto, ON M4G 1X3",
        "postal_code": "M4G 1X3",
        "district": "East York",
        "latitude": 43.7076,
        "longitude": -79.3562,
        "phone": "416-396-4010",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/148/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Variety Village",
        "address": "3701 Danforth Ave, Toronto, ON M1N 2G2",
        "postal_code": "M1N 2G2",
        "district": "Scarborough",
        "latitude": 43.6947,
        "longitude": -79.2765,
        "phone": "416-699-7167",
        "website": "https://www.varietyvillage.ca",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Canlan Ice Sports - York",
        "address": "3770 Chesswood Dr, North York, ON M3J 2W4",
        "postal_code": "M3J 2W4",
        "district": "North York",
        "latitude": 43.7565,
        "longitude": -79.4785,
        "phone": "416-638-7368",
        "website": "https://www.icesports.com/york",
        "is_indoor": True,
        "has_lane_swim": False,  # May not have regular lane swim
    },
    {
        "name": "Goulding Park Recreation Centre",
        "address": "45 Goulding Ave, Toronto, ON M1L 2M1",
        "postal_code": "M1L 2M1",
        "district": "Scarborough",
        "latitude": 43.7119,
        "longitude": -79.2765,
        "phone": "416-396-4046",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/154/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Woburn Community Recreation Centre",
        "address": "1901 Ellesmere Rd, Toronto, ON M1H 2V7",
        "postal_code": "M1H 2V7",
        "district": "Scarborough",
        "latitude": 43.7709,
        "longitude": -79.2344,
        "phone": "416-396-4046",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/160/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Birchmount Community Centre",
        "address": "93 Birchmount Rd, Toronto, ON M1N 3J7",
        "postal_code": "M1N 3J7",
        "district": "Scarborough",
        "latitude": 43.6897,
        "longitude": -79.2672,
        "phone": "416-396-4046",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/131/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Centennial Recreation Centre",
        "address": "1967 Ellesmere Rd, Toronto, ON M1H 2V9",
        "postal_code": "M1H 2V9",
        "district": "Scarborough",
        "latitude": 43.7717,
        "longitude": -79.2303,
        "phone": "416-396-4039",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/135/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "George Bell Arena",
        "address": "145 Orfus Rd, Toronto, ON M6A 1M2",
        "postal_code": "M6A 1M2",
        "district": "North York",
        "latitude": 43.7158,
        "longitude": -79.4455,
        "phone": "416-395-6040",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/153/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Macdonald-Mowat Community Centre",
        "address": "3 Macdonald Ave, Toronto, ON M6R 2A2",
        "postal_code": "M6R 2A2",
        "district": "Toronto West",
        "latitude": 43.6477,
        "longitude": -79.4621,
        "phone": "416-392-0743",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/137/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Eastview Community Centre",
        "address": "86 Blake St, Toronto, ON M4J 3E1",
        "postal_code": "M4J 3E1",
        "district": "East York",
        "latitude": 43.6782,
        "longitude": -79.3447,
        "phone": "416-392-0751",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/143/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Swansea Town Hall",
        "address": "95 Lavinia Ave, Toronto, ON M6S 3H9",
        "postal_code": "M6S 3H9",
        "district": "Toronto West",
        "latitude": 43.6478,
        "longitude": -79.4766,
        "phone": "416-392-0743",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/145/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Weston Lions Pool",
        "address": "2125 Lawrence Ave W, Toronto, ON M9N 3T8",
        "postal_code": "M9N 3T8",
        "district": "North York",
        "latitude": 43.7014,
        "longitude": -79.5217,
        "phone": "416-395-6040",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/158/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Greenwood Community Centre",
        "address": "420 Gerrard St E, Toronto, ON M5A 2G3",
        "postal_code": "M5A 2G3",
        "district": "Toronto Centre",
        "latitude": 43.6601,
        "longitude": -79.3524,
        "phone": "416-392-0744",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/156/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Scadding Court Community Centre",
        "address": "707 Dundas St W, Toronto, ON M5T 2W6",
        "postal_code": "M5T 2W6",
        "district": "Toronto Centre",
        "latitude": 43.6544,
        "longitude": -79.4031,
        "phone": "416-392-0335",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/141/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Flemingdon Park Community Centre",
        "address": "150 Grenoble Dr, Toronto, ON M3C 3E5",
        "postal_code": "M3C 3E5",
        "district": "North York",
        "latitude": 43.7223,
        "longitude": -79.3372,
        "phone": "416-395-6040",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/142/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    
    # Additional facilities - user requested
    {
        "name": "Mary McCormick Recreation Centre",
        "address": "66 Sheridan Ave, Toronto, ON M6K 2H1",
        "postal_code": "M6K 2H1",
        "district": "Toronto West",
        "latitude": 43.6389,
        "longitude": -79.4204,
        "phone": "416-392-0742",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/1/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Norseman Community School and Pool",
        "address": "105 Norseman St, Toronto, ON M8Z 2R3",
        "postal_code": "M8Z 2R3",
        "district": "Etobicoke",
        "latitude": 43.6158,
        "longitude": -79.5211,
        "phone": "416-394-8719",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/2/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Harrison Pool",
        "address": "15 Stephanie St, Toronto, ON M1M 2J9",
        "postal_code": "M1M 2J9",
        "district": "Scarborough",
        "latitude": 43.7243,
        "longitude": -79.2364,
        "phone": "416-392-7984",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/3/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Trinity Community Recreation Centre",
        "address": "155 Crawford St, Toronto, ON M6J 2V5",
        "postal_code": "M6J 2V5",
        "district": "Toronto West",
        "latitude": 43.6477,
        "longitude": -79.4235,
        "phone": "416-392-0743",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/4/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Joseph J. Piccininni Community Recreation Centre",
        "address": "1369 St. Clair Ave W, Toronto, ON M6E 1C5",
        "postal_code": "M6E 1C5",
        "district": "Toronto West",
        "latitude": 43.6780,
        "longitude": -79.4523,
        "phone": "416-392-0036",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/5/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Swansea Community Recreation Centre",
        "address": "15 Waller Ave, Toronto, ON M6S 2X7",
        "postal_code": "M6S 2X7",
        "district": "Toronto West",
        "latitude": 43.6516,
        "longitude": -79.4771,
        "phone": "416-392-6796",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/6/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Pam McConnell Aquatic Centre",
        "address": "640 Dundas St E, Toronto, ON M5A 2B9",
        "postal_code": "M5A 2B9",
        "district": "Toronto Centre",
        "latitude": 43.6590,
        "longitude": -79.3583,
        "phone": "416-338-2237",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/7/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Annette Community Recreation Centre",
        "address": "333 Annette St, Toronto, ON M6P 1R2",
        "postal_code": "M6P 1R2",
        "district": "Toronto West",
        "latitude": 43.6618,
        "longitude": -79.4682,
        "phone": "416-392-0736",
        "website": "https://www.toronto.ca/data/parks/prd/facilities/complex/8/index.html",
        "is_indoor": True,
        "has_lane_swim": True,
    },
]


def get_all_indoor_pools():
    """Return list of all indoor pools."""
    return [p for p in TORONTO_INDOOR_POOLS if p.get("is_indoor", False)]


def get_lane_swim_pools():
    """Return list of pools with lane swim."""
    return [p for p in TORONTO_INDOOR_POOLS if p.get("has_lane_swim", False)]


def get_pools_by_district(district):
    """Return list of pools in a specific district."""
    return [p for p in TORONTO_INDOOR_POOLS if p.get("district") == district]


def get_pool_count():
    """Return count of pools."""
    return len(TORONTO_INDOOR_POOLS)

