"""
Comprehensive list of Toronto community centers with indoor swimming pools.
This data is compiled from Toronto Parks, Forestry & Recreation facilities.
"""

TORONTO_INDOOR_POOLS = [
    # Downtown Core
    {
        "name": "Regent Park Aquatic Centre",
        "address": "402 Shuter St, Toronto, ON M5A 1X1",
        "postal_code": "M5A 1X1",
        "district": "Toronto Centre",
        "latitude": 43.6581255,
        "longitude": -79.3617443,
        "phone": "416-392-0740",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=627&title=Regent-Park-Aquatic-Centre",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Toronto Pan Am Sports Centre",
        "address": "875 Morningside Ave, Toronto, ON M1C 0C7",
        "postal_code": "M1C 0C7",
        "district": "Scarborough",
        "latitude": 43.7907754,
        "longitude": -79.1936912,
        "phone": "416-287-7765",
        "website": "https://www.tpasc.ca",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Scarborough Civic Centre Aquatic Complex",
        "address": "150 Borough Dr, Toronto, ON M1P 4N7",
        "postal_code": "M1P 4N7",
        "district": "Scarborough",
        "latitude": 43.7729485,
        "longitude": -79.2575865,
        "phone": "416-396-4039",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=668&title=Scarborough-Civic-Centre-Aquatic-Complex",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    
    # North York
    {
        "name": "North York YMCA",
        "address": "20 Avondale Ave, Toronto, ON M2N 2S1",
        "postal_code": "M2N 2S1",
        "district": "North York",
        "latitude": 43.758472,
        "longitude": -79.409285,
        "phone": "416-250-0200",
        "website": "https://ymcagta.org/find-a-y/north-york-ymca",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Giovanni Caboto Community Centre",
        "address": "1550 Bathurst St, Toronto, ON M5P 3H8",
        "postal_code": "M5P 3H8",
        "district": "Toronto Centre",
        "latitude": 43.6853402,
        "longitude": -79.4195797,
        "phone": "416-392-0744",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=323&title=Giovanni-Caboto-Community-Centre",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Grandravine Community Recreation Centre",
        "address": "23 Grandravine Dr, Toronto, ON M3N 1H3",
        "postal_code": "M3N 1H3",
        "district": "North York",
        "latitude": 43.7517796,
        "longitude": -79.4896362,
        "phone": "416-395-6040",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=347&title=Grandravine-Community-Recreation-Centre",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Fairview Community Pool",
        "address": "1803 Sheppard Ave E, Toronto, ON M2J 5B1",
        "postal_code": "M2J 5B1",
        "district": "North York",
        "latitude": 43.7953012,
        "longitude": -79.2318586,
        "phone": "416-395-6040",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=270&title=Fairview-Community-Pool",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    
    # Etobicoke
    {
        "name": "Etobicoke Olympium",
        "address": "590 Rathburn Rd, Etobicoke, ON M9C 3T3",
        "postal_code": "M9C 3T3",
        "district": "Etobicoke",
        "latitude": 43.6496639,
        "longitude": -79.5835018,
        "phone": "416-394-8754",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=261&title=Etobicoke-Olympium",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Burnhamthorpe Community Centre",
        "address": "20 Winterton Dr, Etobicoke, ON M9B 3P2",
        "postal_code": "M9B 3P2",
        "district": "Etobicoke",
        "latitude": 43.6721591,
        "longitude": -79.5576798,
        "phone": "416-394-8840",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=127&title=Burnhamthorpe-Community-Centre",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "York Recreation Centre",
        "address": "22 Guestville Ave, Toronto, ON M8W 4E9",
        "postal_code": "M8W 4E9",
        "district": "Etobicoke",
        "latitude": 43.627689,
        "longitude": -79.545319,
        "phone": "416-392-7145",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=3326&title=York-Recreation-Centre",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Westway Community Centre",
        "address": "40 Hawksbury Dr, Etobicoke, ON M9V 4M4",
        "postal_code": "M9V 4M4",
        "district": "Etobicoke",
        "latitude": 43.7384,
        "longitude": -79.5820,
        "phone": "416-394-8840",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=1229&title=Westway-Community-Centre",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    
    # Scarborough
    {
        "name": "McGregor Park Community Centre",
        "address": "2231 Lawrence Ave E, Toronto, ON M1P 2P7",
        "postal_code": "M1P 2P7",
        "district": "Scarborough",
        "latitude": 43.747601,
        "longitude": -79.2800543,
        "phone": "416-396-4046",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=532&title=McGregor-Park-Community-Centre",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "L'Amoreaux Recreation Centre",
        "address": "2000 McNicoll Ave, Toronto, ON M1V 5L7",
        "postal_code": "M1V 5L7",
        "district": "Scarborough",
        "latitude": 43.8120209,
        "longitude": -79.3049772,
        "phone": "416-396-4046",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=481&title=LAmoreaux-Recreation-Centre",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Malvern Recreation Centre",
        "address": "30 Sewells Rd, Toronto, ON M1B 3G5",
        "postal_code": "M1B 3G5",
        "district": "Scarborough",
        "latitude": 43.8085674,
        "longitude": -79.2161218,
        "phone": "416-396-4046",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=511&title=Malvern-Recreation-Centre",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Albert Campbell District Park Pool",
        "address": "496 Birchmount Rd, Toronto, ON M1K 1M9",
        "postal_code": "M1K 1M9",
        "district": "Scarborough",
        "latitude": 43.7080605,
        "longitude": -79.269299,
        "phone": "416-396-4046",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=10&title=Albert-Campbell-District-Park-Pool",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    
    # East York
    {
        "name": "Stan Wadlow Clubhouse",
        "address": "373 Cedarvale Ave, Toronto, ON M4C 4K7",
        "postal_code": "M4C 4K7",
        "district": "East York",
        "latitude": 43.6983542,
        "longitude": -79.3150874,
        "phone": "416-392-0751",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=752&title=Stan-Wadlow-Clubhouse",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Jimmie Simpson Recreation Centre",
        "address": "870 Queen St E, Toronto, ON M4M 1J3",
        "postal_code": "M4M 1J3",
        "district": "Toronto East",
        "latitude": 43.660407,
        "longitude": -79.345308,
        "phone": "416-392-0751",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=476&title=Jimmie-Simpson-Recreation-Centre",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    
    # Central Toronto
    {
        "name": "Miles Nadal JCC",
        "address": "750 Spadina Ave, Toronto, ON M5S 2J2",
        "postal_code": "M5S 2J2",
        "district": "Toronto Centre",
        "latitude": 43.6662039,
        "longitude": -79.404189,
        "phone": "416-924-6211",
        "website": "https://mnjcc.org",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Toronto Athletic Club",
        "address": "1 Shoreham Dr, Toronto, ON M3N 1S4",
        "postal_code": "M3N 1S4",
        "district": "North York",
        "latitude": 43.7707291,
        "longitude": -79.5152026,
        "phone": "416-630-9000",
        "website": "https://www.tac.com",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Wallace Emerson Community Centre",
        "address": "1260 Dufferin St, Toronto, ON M6H 4C3",
        "postal_code": "M6H 4C3",
        "district": "Toronto Centre",
        "latitude": 43.6674695,
        "longitude": -79.439134,
        "phone": "416-392-0743",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=1209&title=Wallace-Emerson-Community-Centre",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "High Park Pool",
        "address": "375 Colborne Lodge Dr, Toronto, ON M6R 2Z3",
        "postal_code": "M6R 2Z3",
        "district": "Toronto West",
        "latitude": 43.6512348,
        "longitude": -79.4636347,
        "phone": "416-392-1111",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=403&title=High-Park-Pool",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    
    # Additional Community Centers
    {
        "name": "Oriole Community Centre",
        "address": "2975 Don Mills Rd W, Toronto, ON M2J 3B7",
        "postal_code": "M2J 3B7",
        "district": "North York",
        "latitude": 43.783906,
        "longitude": -79.3526845,
        "phone": "416-395-6040",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=590&title=Oriole-Community-Centre",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Albion Neighbourhood Services",
        "address": "1530 Albion Rd, Etobicoke, ON M9V 1B4",
        "postal_code": "M9V 1B4",
        "district": "Etobicoke",
        "latitude": 43.7412504,
        "longitude": -79.5833046,
        "phone": "416-394-8840",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=13&title=Albion-Neighbourhood-Services",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Moss Park Arena and Recreation Centre",
        "address": "140 Sherbourne St, Toronto, ON M5A 2R2",
        "postal_code": "M5A 2R2",
        "district": "Toronto Centre",
        "latitude": 43.6549624,
        "longitude": -79.3702748,
        "phone": "416-392-0744",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=557&title=Moss-Park-Arena-and-Recreation-Centre",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Matty Eckler Recreation Centre",
        "address": "953 Gerrard St E, Toronto, ON M4M 1Z4",
        "postal_code": "M4M 1Z4",
        "district": "Toronto East",
        "latitude": 43.6678944,
        "longitude": -79.3397856,
        "phone": "416-392-0751",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=528&title=Matty-Eckler-Recreation-Centre",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Leaside Memorial Community Gardens",
        "address": "1073 Millwood Rd, Toronto, ON M4G 1X3",
        "postal_code": "M4G 1X3",
        "district": "East York",
        "latitude": 43.701761,
        "longitude": -79.3608884,
        "phone": "416-396-4010",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=491&title=Leaside-Memorial-Community-Gardens",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Variety Village",
        "address": "3701 Danforth Ave, Toronto, ON M1N 2G2",
        "postal_code": "M1N 2G2",
        "district": "Scarborough",
        "latitude": 43.6985075,
        "longitude": -79.2593658,
        "phone": "416-699-7167",
        "website": "https://www.varietyvillage.ca",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Canlan Ice Sports - York",
        "address": "3770 Chesswood Dr, North York, ON M3J 2W4",
        "postal_code": "M3J 2W4",
        "district": "North York",
        "latitude": 43.7644618,
        "longitude": -79.4766371,
        "phone": "416-638-7368",
        "website": "https://www.icesports.com/york",
        "is_indoor": True,
        "has_lane_swim": False,  # May not have regular lane swim
    },
    {
        "name": "Goulding Park Recreation Centre",
        "address": "45 Goulding Ave, Toronto, ON M1L 2M1",
        "postal_code": "M1L 2M1",
        "district": "Scarborough",
        "latitude": 43.790698,
        "longitude": -79.4220765,
        "phone": "416-396-4046",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=338&title=Goulding-Park-Recreation-Centre",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Woburn Community Recreation Centre",
        "address": "1901 Ellesmere Rd, Toronto, ON M1H 2V7",
        "postal_code": "M1H 2V7",
        "district": "Scarborough",
        "latitude": 43.7747022,
        "longitude": -79.2393401,
        "phone": "416-396-4046",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=1236&title=Woburn-Community-Recreation-Centre",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Birchmount Community Centre",
        "address": "93 Birchmount Rd, Toronto, ON M1N 3J7",
        "postal_code": "M1N 3J7",
        "district": "Scarborough",
        "latitude": 43.6956191,
        "longitude": -79.2632036,
        "phone": "416-396-4046",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=75&title=Birchmount-Community-Centre",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Centennial Recreation Centre",
        "address": "1967 Ellesmere Rd, Toronto, ON M1H 2V9",
        "postal_code": "M1H 2V9",
        "district": "Scarborough",
        "latitude": 43.7755592,
        "longitude": -79.2351695,
        "phone": "416-396-4039",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=143&title=Centennial-Recreation-Centre",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "George Bell Arena",
        "address": "145 Orfus Rd, Toronto, ON M6A 1M2",
        "postal_code": "M6A 1M2",
        "district": "North York",
        "latitude": 43.7198016,
        "longitude": -79.4588922,
        "phone": "416-395-6040",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=314&title=George-Bell-Arena",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Macdonald-Mowat Community Centre",
        "address": "3 Macdonald Ave, Toronto, ON M6R 2A2",
        "postal_code": "M6R 2A2",
        "district": "Toronto West",
        "latitude": 43.7033512,
        "longitude": -79.508891,
        "phone": "416-392-0743",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=500&title=Macdonald-Mowat-Community-Centre",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Eastview Community Centre",
        "address": "86 Blake St, Toronto, ON M4J 3E1",
        "postal_code": "M4J 3E1",
        "district": "East York",
        "latitude": 43.6750332,
        "longitude": -79.3398185,
        "phone": "416-392-0751",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=256&title=Eastview-Community-Centre",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Swansea Town Hall",
        "address": "95 Lavinia Ave, Toronto, ON M6S 3H9",
        "postal_code": "M6S 3H9",
        "district": "Toronto West",
        "latitude": 43.647611,
        "longitude": -79.477856,
        "phone": "416-392-0743",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=1085&title=Swansea-Town-Hall",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Weston Lions Pool",
        "address": "2125 Lawrence Ave W, Toronto, ON M9N 3T8",
        "postal_code": "M9N 3T8",
        "district": "North York",
        "latitude": 43.6985856,
        "longitude": -79.5181217,
        "phone": "416-395-6040",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=1225&title=Weston-Lions-Pool",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Greenwood Community Centre",
        "address": "420 Gerrard St E, Toronto, ON M5A 2G3",
        "postal_code": "M5A 2G3",
        "district": "Toronto Centre",
        "latitude": 43.6883151,
        "longitude": -79.280067,
        "phone": "416-392-0744",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=353&title=Greenwood-Community-Centre",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Scadding Court Community Centre",
        "address": "707 Dundas St W, Toronto, ON M5T 2W6",
        "postal_code": "M5T 2W6",
        "district": "Toronto Centre",
        "latitude": 43.6516689,
        "longitude": -79.4044282,
        "phone": "416-392-0335",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=669&title=Scadding-Court-Community-Centre",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Flemingdon Park Community Centre",
        "address": "150 Grenoble Dr, Toronto, ON M3C 3E5",
        "postal_code": "M3C 3E5",
        "district": "North York",
        "latitude": 43.7135548,
        "longitude": -79.3263608,
        "phone": "416-395-6040",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=280&title=Flemingdon-Park-Community-Centre",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    
    # Additional facilities - user requested
    {
        "name": "Mary McCormick Recreation Centre",
        "address": "66 Sheridan Ave, Toronto, ON M6K 2H1",
        "postal_code": "M6K 2H1",
        "district": "Toronto West",
        "latitude": 43.6473893,
        "longitude": -79.4331344,
        "phone": "416-392-0742",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=522&title=Mary-McCormick-Recreation-Centre",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Norseman Community School and Pool",
        "address": "105 Norseman St, Toronto, ON M8Z 2R3",
        "postal_code": "M8Z 2R3",
        "district": "Etobicoke",
        "latitude": 43.6341938,
        "longitude": -79.5162384,
        "phone": "416-394-8719",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=797&title=Norseman-Community-School-and-Pool",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Harrison Pool",
        "address": "15 Stephanie St, Toronto, ON M1M 2J9",
        "postal_code": "M1M 2J9",
        "district": "Scarborough",
        "latitude": 43.6510937,
        "longitude": -79.3908315,
        "phone": "416-392-7984",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=382&title=Harrison-Pool",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Trinity Community Recreation Centre",
        "address": "155 Crawford St, Toronto, ON M6J 2V5",
        "postal_code": "M6J 2V5",
        "district": "Toronto West",
        "latitude": 43.646243,
        "longitude": -79.4149001,
        "phone": "416-392-0743",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=1167&title=Trinity-Community-Recreation-Centre",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Joseph J. Piccininni Community Recreation Centre",
        "address": "1369 St. Clair Ave W, Toronto, ON M6E 1C5",
        "postal_code": "M6E 1C5",
        "district": "Toronto West",
        "latitude": 43.6753158,
        "longitude": -79.4515427,
        "phone": "416-392-0036",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=509&title=Joseph-J-Piccininni-Community-Recreation-Centre",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Swansea Community Recreation Centre",
        "address": "15 Waller Ave, Toronto, ON M6S 2X7",
        "postal_code": "M6S 2X7",
        "district": "Toronto West",
        "latitude": 43.6439532,
        "longitude": -79.4767859,
        "phone": "416-392-6796",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=696&title=Swansea-Community-Recreation-Centre",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Pam McConnell Aquatic Centre",
        "address": "640 Dundas St E, Toronto, ON M5A 2B9",
        "postal_code": "M5A 2B9",
        "district": "Toronto Centre",
        "latitude": 43.6612253,
        "longitude": -79.3610976,
        "phone": "416-338-2237",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=2012&title=Pam-McConnell-Aquatic-Centre",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Annette Community Recreation Centre",
        "address": "333 Annette St, Toronto, ON M6P 1R2",
        "postal_code": "M6P 1R2",
        "district": "Toronto West",
        "latitude": 43.6611203,
        "longitude": -79.4736935,
        "phone": "416-392-0736",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=33&title=Annette-Community-Recreation-Centre",
        "is_indoor": True,
        "has_lane_swim": True,
    },
]


def get_all_indoor_pools():
    """Return list of all indoor pools."""
    return [p for p in TORONTO_INDOOR_POOLS if p.get("is_indoor", False)]


def get_lane_swim_pools():
    """Return list of pools with lane swim."""
    return [p for p in TORONTO_INDOOR_POOLS if p.get("has_lane_swim", False)]


def get_pools_by_district(district):
    """Return list of pools in a specific district."""
    return [p for p in TORONTO_INDOOR_POOLS if p.get("district") == district]


def get_pool_count():
    """Return count of pools."""
    return len(TORONTO_INDOOR_POOLS)

