"""
Comprehensive list of Toronto community centers with indoor swimming pools.
This data is compiled from Toronto Parks, Forestry & Recreation facilities.
"""

TORONTO_INDOOR_POOLS = [
    # Downtown Core
    {
        "name": "Regent Park Aquatic Centre",
        "address": "402 Shuter St, Toronto, ON M5A 1X1",
        "postal_code": "M5A 1X1",
        "district": "Toronto Centre",
        "latitude": 43.6581255,
        "longitude": -79.3617443,
        "phone": "416-392-0740",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=3502",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Toronto Pan Am Sports Centre",
        "address": "875 Morningside Ave, Toronto, ON M1C 0C7",
        "postal_code": "M1C 0C7",
        "district": "Scarborough",
        "latitude": 43.7907754,
        "longitude": -79.1936912,
        "phone": "416-287-7765",
        "website": "https://www.tpasc.ca",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Scarborough Civic Centre Aquatic Complex",
        "address": "150 Borough Dr, Toronto, ON M1P 4N7",
        "postal_code": "M1P 4N7",
        "district": "Scarborough",
        "latitude": 43.7729485,
        "longitude": -79.2575865,
        "phone": "416-396-4039",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=1099",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    
    # North York
    {
        "name": "North York YMCA",
        "address": "20 Avondale Ave, Toronto, ON M2N 2S1",
        "postal_code": "M2N 2S1",
        "district": "North York",
        "latitude": 43.758472,
        "longitude": -79.409285,
        "phone": "416-250-0200",
        "website": "https://ymcagta.org/find-a-y/north-york-ymca",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Giovanni Caboto Community Centre",
        "address": "1550 Bathurst St, Toronto, ON M5P 3H8",
        "postal_code": "M5P 3H8",
        "district": "Toronto Centre",
        "latitude": 43.6853402,
        "longitude": -79.4195797,
        "phone": "416-392-0744",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=2639",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Grandravine Community Recreation Centre",
        "address": "23 Grandravine Dr, Toronto, ON M3N 1H3",
        "postal_code": "M3N 1H3",
        "district": "North York",
        "latitude": 43.7517796,
        "longitude": -79.4896362,
        "phone": "416-395-6040",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=647",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 647,
    },
    {
        "name": "Fairview Community Pool",
        "address": "1803 Sheppard Ave E, Toronto, ON M2J 5B1",
        "postal_code": "M2J 5B1",
        "district": "North York",
        "latitude": 43.7953012,
        "longitude": -79.2318586,
        "phone": "416-395-6040",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=270&title=Fairview-Community-Pool",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    
    # Etobicoke
    {
        "name": "Etobicoke Olympium",
        "address": "590 Rathburn Rd, Etobicoke, ON M9C 3T3",
        "postal_code": "M9C 3T3",
        "district": "Etobicoke",
        "latitude": 43.6496639,
        "longitude": -79.5835018,
        "phone": "416-394-8754",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=892",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Burnhamthorpe Community Centre",
        "address": "20 Winterton Dr, Etobicoke, ON M9B 3P2",
        "postal_code": "M9B 3P2",
        "district": "Etobicoke",
        "latitude": 43.6721591,
        "longitude": -79.5576798,
        "phone": "416-394-8840",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=127&title=Burnhamthorpe-Community-Centre",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "York Recreation Centre",
        "address": "115 Black Creek Dr, Toronto, ON M6N 1A6",
        "postal_code": "M6N 1A6",
        "district": "Etobicoke York",
        "latitude": 43.6889,
        "longitude": -79.4789,
        "phone": "416-392-9675",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=3501",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Westway Community Centre",
        "address": "40 Hawksbury Dr, Etobicoke, ON M9V 4M4",
        "postal_code": "M9V 4M4",
        "district": "Etobicoke",
        "latitude": 43.7384,
        "longitude": -79.5820,
        "phone": "416-394-8840",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=1229&title=Westway-Community-Centre",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    
    # Scarborough
    {
        "name": "McGregor Park Community Centre",
        "address": "2231 Lawrence Ave E, Toronto, ON M1P 2P7",
        "postal_code": "M1P 2P7",
        "district": "Scarborough",
        "latitude": 43.747601,
        "longitude": -79.2800543,
        "phone": "416-396-4046",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=506",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 506,
    },
    {
        "name": "L'Amoreaux Recreation Centre",
        "address": "2000 McNicoll Ave, Toronto, ON M1V 5L7",
        "postal_code": "M1V 5L7",
        "district": "Scarborough",
        "latitude": 43.8120209,
        "longitude": -79.3049772,
        "phone": "416-396-4046",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=788",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Malvern Recreation Centre",
        "address": "30 Sewells Rd, Toronto, ON M1B 3G5",
        "postal_code": "M1B 3G5",
        "district": "Scarborough",
        "latitude": 43.8085674,
        "longitude": -79.2161218,
        "phone": "416-396-4046",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=702",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Albert Campbell District Park Pool",
        "address": "496 Birchmount Rd, Toronto, ON M1K 1M9",
        "postal_code": "M1K 1M9",
        "district": "Scarborough",
        "latitude": 43.7080605,
        "longitude": -79.269299,
        "phone": "416-396-4046",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=10&title=Albert-Campbell-District-Park-Pool",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    
    # East York
    {
        "name": "Stan Wadlow Clubhouse",
        "address": "373 Cedarvale Ave, Toronto, ON M4C 4K7",
        "postal_code": "M4C 4K7",
        "district": "East York",
        "latitude": 43.6983542,
        "longitude": -79.3150874,
        "phone": "416-392-0751",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=297",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Jimmie Simpson Recreation Centre",
        "address": "870 Queen St E, Toronto, ON M4M 1J3",
        "postal_code": "M4M 1J3",
        "district": "Toronto East",
        "latitude": 43.660407,
        "longitude": -79.345308,
        "phone": "416-392-0751",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=58",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    
    # Central Toronto
    {
        "name": "Miles Nadal JCC",
        "address": "750 Spadina Ave, Toronto, ON M5S 2J2",
        "postal_code": "M5S 2J2",
        "district": "Toronto Centre",
        "latitude": 43.6662039,
        "longitude": -79.404189,
        "phone": "416-924-6211",
        "website": "https://mnjcc.org",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Toronto Athletic Club",
        "address": "1 Shoreham Dr, Toronto, ON M3N 1S4",
        "postal_code": "M3N 1S4",
        "district": "North York",
        "latitude": 43.7707291,
        "longitude": -79.5152026,
        "phone": "416-630-9000",
        "website": "https://www.tac.com",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Wallace Emerson Community Centre",
        "address": "1260 Dufferin St, Toronto, ON M6H 4C3",
        "postal_code": "M6H 4C3",
        "district": "Toronto Centre",
        "latitude": 43.6674695,
        "longitude": -79.439134,
        "phone": "416-392-0743",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=294",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "High Park Pool",
        "address": "375 Colborne Lodge Dr, Toronto, ON M6R 2Z3",
        "postal_code": "M6R 2Z3",
        "district": "Toronto West",
        "latitude": 43.6512348,
        "longitude": -79.4636347,
        "phone": "416-392-1111",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=77",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 77,
    },
    
    # Additional Community Centers
    {
        "name": "Oriole Community Centre",
        "address": "2975 Don Mills Rd W, Toronto, ON M2J 3B7",
        "postal_code": "M2J 3B7",
        "district": "North York",
        "latitude": 43.783906,
        "longitude": -79.3526845,
        "phone": "416-395-6040",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=714",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 714,
    },
    {
        "name": "Albion Neighbourhood Services",
        "address": "1530 Albion Rd, Etobicoke, ON M9V 1B4",
        "postal_code": "M9V 1B4",
        "district": "Etobicoke",
        "latitude": 43.7412504,
        "longitude": -79.5833046,
        "phone": "416-394-8840",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=800",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Moss Park Arena and Recreation Centre",
        "address": "140 Sherbourne St, Toronto, ON M5A 2R2",
        "postal_code": "M5A 2R2",
        "district": "Toronto Centre",
        "latitude": 43.6549624,
        "longitude": -79.3702748,
        "phone": "416-392-0744",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=3491",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Matty Eckler Recreation Centre",
        "address": "953 Gerrard St E, Toronto, ON M4M 1Z4",
        "postal_code": "M4M 1Z4",
        "district": "Toronto East",
        "latitude": 43.6678944,
        "longitude": -79.3397856,
        "phone": "416-392-0751",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=234",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Leaside Memorial Community Gardens",
        "address": "1073 Millwood Rd, Toronto, ON M4G 1X3",
        "postal_code": "M4G 1X3",
        "district": "East York",
        "latitude": 43.701761,
        "longitude": -79.3608884,
        "phone": "416-396-4010",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=789",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Variety Village",
        "address": "3701 Danforth Ave, Toronto, ON M1N 2G2",
        "postal_code": "M1N 2G2",
        "district": "Scarborough",
        "latitude": 43.6985075,
        "longitude": -79.2593658,
        "phone": "416-699-7167",
        "website": "https://www.varietyvillage.ca",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Canlan Ice Sports - York",
        "address": "3770 Chesswood Dr, North York, ON M3J 2W4",
        "postal_code": "M3J 2W4",
        "district": "North York",
        "latitude": 43.7644618,
        "longitude": -79.4766371,
        "phone": "416-638-7368",
        "website": "https://www.icesports.com/york",
        "is_indoor": True,
        "has_lane_swim": False,  # May not have regular lane swim
    },
    {
        "name": "Goulding Community Recreation Centre",
        "address": "45 Goulding Ave, Toronto, ON M2M 1K8",
        "postal_code": "M2M 1K8",
        "district": "North York",
        "latitude": 43.7906980,
        "longitude": -79.4220765,
        "phone": "416-395-6040",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=643",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 643,
    },
    {
        "name": "Woburn Community Recreation Centre",
        "address": "1901 Ellesmere Rd, Toronto, ON M1H 2V7",
        "postal_code": "M1H 2V7",
        "district": "Scarborough",
        "latitude": 43.7747022,
        "longitude": -79.2393401,
        "phone": "416-396-4046",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=1236&title=Woburn-Community-Recreation-Centre",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Birchmount Community Centre",
        "address": "93 Birchmount Rd, Toronto, ON M1N 3J7",
        "postal_code": "M1N 3J7",
        "district": "Scarborough",
        "latitude": 43.6956191,
        "longitude": -79.2632036,
        "phone": "416-396-4046",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=507",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Centennial Recreation Centre",
        "address": "1967 Ellesmere Rd, Toronto, ON M1H 2V9",
        "postal_code": "M1H 2V9",
        "district": "Scarborough",
        "latitude": 43.7755592,
        "longitude": -79.2351695,
        "phone": "416-396-4039",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=537",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "George Bell Arena",
        "address": "215 Ryding Ave, Toronto, ON M6N 1H3",
        "postal_code": "M6N 1H3",
        "district": "Etobicoke York",
        "latitude": 43.6695173,
        "longitude": -79.4760761,
        "phone": "416-394-8741",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=3488",
        "is_indoor": True,
        "has_lane_swim": False,  # Arena primarily for ice sports, verify pool availability
    },
    {
        "name": "Macdonald-Mowat Community Centre",
        "address": "3 Macdonald Ave, Toronto, ON M6R 2A2",
        "postal_code": "M6R 2A2",
        "district": "Toronto West",
        "latitude": 43.7033512,
        "longitude": -79.508891,
        "phone": "416-392-0743",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=500&title=Macdonald-Mowat-Community-Centre",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Eastview Community Centre",
        "address": "86 Blake St, Toronto, ON M4J 3E1",
        "postal_code": "M4J 3E1",
        "district": "East York",
        "latitude": 43.6750332,
        "longitude": -79.3398185,
        "phone": "416-392-0751",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=732",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Swansea Town Hall",
        "address": "95 Lavinia Ave, Toronto, ON M6S 3H9",
        "postal_code": "M6S 3H9",
        "district": "Toronto West",
        "latitude": 43.647611,
        "longitude": -79.477856,
        "phone": "416-392-0743",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=1085&title=Swansea-Town-Hall",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Weston Lions Pool",
        "address": "2125 Lawrence Ave W, Toronto, ON M9N 3T8",
        "postal_code": "M9N 3T8",
        "district": "North York",
        "latitude": 43.6985856,
        "longitude": -79.5181217,
        "phone": "416-395-6040",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=508",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 508,
    },
    {
        "name": "Greenwood Park Pool",
        "address": "150 Greenwood Ave, Toronto, ON M4L 3A2",
        "postal_code": "M4L 3A2",
        "district": "Toronto East",
        "latitude": 43.6777838,
        "longitude": -79.3308316,
        "phone": "416-392-0751",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=70",
        "is_indoor": False,  # Outdoor pool per toronto.ca
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Scadding Court Community Centre",
        "address": "707 Dundas St W, Toronto, ON M5T 2W6",
        "postal_code": "M5T 2W6",
        "district": "Toronto Centre",
        "latitude": 43.6516689,
        "longitude": -79.4044282,
        "phone": "416-392-0335",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=1098",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Flemingdon Park Community Centre",
        "address": "150 Grenoble Dr, Toronto, ON M3C 3E5",
        "postal_code": "M3C 3E5",
        "district": "North York",
        "latitude": 43.7135548,
        "longitude": -79.3263608,
        "phone": "416-395-6040",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=585",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    
    # Additional facilities - user requested
    {
        "name": "Mary McCormick Recreation Centre",
        "address": "66 Sheridan Ave, Toronto, ON M6K 2H1",
        "postal_code": "M6K 2H1",
        "district": "Toronto West",
        "latitude": 43.6473893,
        "longitude": -79.4331344,
        "phone": "416-392-0742",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=100",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Norseman Community School and Pool",
        "address": "105 Norseman St, Toronto, ON M8Z 2R3",
        "postal_code": "M8Z 2R3",
        "district": "Etobicoke",
        "latitude": 43.6341938,
        "longitude": -79.5162384,
        "phone": "416-394-8719",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=797",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Harrison Pool",
        "address": "15 Stephanie St, Toronto, ON M5T 1B1",
        "postal_code": "M5T 1B1",
        "district": "Toronto Centre",
        "latitude": 43.6510937,
        "longitude": -79.3908315,
        "phone": "416-392-7984",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=45",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Trinity Community Recreation Centre",
        "address": "155 Crawford St, Toronto, ON M6J 2V5",
        "postal_code": "M6J 2V5",
        "district": "Toronto West",
        "latitude": 43.646243,
        "longitude": -79.4149001,
        "phone": "416-392-0743",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=287",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Joseph J. Piccininni Community Recreation Centre",
        "address": "1369 St. Clair Ave W, Toronto, ON M6E 1C5",
        "postal_code": "M6E 1C5",
        "district": "Toronto West",
        "latitude": 43.6753158,
        "longitude": -79.4515427,
        "phone": "416-392-0036",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=509",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Swansea Community Recreation Centre",
        "address": "15 Waller Ave, Toronto, ON M6S 2X7",
        "postal_code": "M6S 2X7",
        "district": "Toronto West",
        "latitude": 43.6439532,
        "longitude": -79.4767859,
        "phone": "416-392-6796",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=282",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Pam McConnell Aquatic Centre",
        "address": "640 Dundas St E, Toronto, ON M5A 2B9",
        "postal_code": "M5A 2B9",
        "district": "Toronto Centre",
        "latitude": 43.6612253,
        "longitude": -79.3610976,
        "phone": "416-338-2237",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=2012",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Annette Community Recreation Centre",
        "address": "333 Annette St, Toronto, ON M6P 1R2",
        "postal_code": "M6P 1R2",
        "district": "Toronto West",
        "latitude": 43.6611203,
        "longitude": -79.4736935,
        "phone": "416-392-0736",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=17",
        "is_indoor": True,
        "has_lane_swim": True,
    },
    {
        "name": "Ourland Park Outdoor Pool",
        "address": "18 Ourland Ave, Toronto, ON M8Z 1N4",
        "postal_code": "M8Z 1N4",
        "district": "Etobicoke York",
        "latitude": 43.6186374,
        "longitude": -79.5091642,
        "phone": "416-394-8700",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=857&title=Ourland-Park",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
    },

    # Outdoor pools auto-discovered from Toronto Open Data (issue #178)
    {
        "name": "Alexandra Park",
        "address": "275 Bathurst St, Toronto, ON",
        "postal_code": "",
        "district": "Toronto and East York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=31",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 31,
    },
    {
        "name": "Amesbury Sports Complex",
        "address": "155 Culford Rd., Toronto, ON",
        "postal_code": "M6M 4K6",
        "district": "Etobicoke York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=480",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 480,
    },
    {
        "name": "Amos Waites Park",
        "address": "2441 Lake Shore Blvd W, Toronto, ON",
        "postal_code": "",
        "district": "Etobicoke York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=939",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 939,
    },
    {
        "name": "Broadlands Community Recreation Centre",
        "address": "19 Castlegrove Blvd, Toronto, ON",
        "postal_code": "M3A 1K9",
        "district": "North York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=7",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 7,
    },
    {
        "name": "Christie Pits Park",
        "address": "750 Bloor St W, Toronto, ON",
        "postal_code": "",
        "district": "Toronto and East York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=196",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 196,
    },
    {
        "name": "Dennis Flynn Park",
        "address": "370 The West Mall, Toronto, ON",
        "postal_code": "",
        "district": "Etobicoke York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=2642",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 2642,
    },
    {
        "name": "Domenico DiLuca Community Recreation Centre",
        "address": "25 Stanley Rd, Toronto, ON",
        "postal_code": "M3N 1C2",
        "district": "Etobicoke York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=760",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 760,
    },
    {
        "name": "Donald D. Summerville Olympic Pools",
        "address": "1867 Lake Shore Blvd E, Toronto, ON",
        "postal_code": "",
        "district": "Toronto and East York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=437",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 437,
    },
    {
        "name": "Driftwood Community Recreation Centre",
        "address": "4401 Jane St, Toronto, ON",
        "postal_code": "M3N 2K3",
        "district": "Etobicoke York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=575",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 575,
    },
    {
        "name": "Earlscourt Park",
        "address": "1200 Lansdowne Ave, Toronto, ON",
        "postal_code": "",
        "district": "Toronto and East York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=514",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 514,
    },
    {
        "name": "Eringate Park",
        "address": "121 Wellesworth Dr, Toronto, ON",
        "postal_code": "",
        "district": "Etobicoke York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=840",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 840,
    },
    {
        "name": "Fairbank Memorial Park",
        "address": "2213 Dufferin St, Toronto, ON",
        "postal_code": "",
        "district": "Toronto and East York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=502",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 502,
    },
    {
        "name": "Fairhaven Park",
        "address": "100 Golfwood Hts, Toronto, ON",
        "postal_code": "",
        "district": "Etobicoke York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=1007",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 1007,
    },
    {
        "name": "Flagstaff Park",
        "address": "42 Mercury Rd, Toronto, ON",
        "postal_code": "",
        "district": "Etobicoke York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=963",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 963,
    },
    {
        "name": "Gihon Spring Park",
        "address": "75 Gihon Spring Dr, Toronto, ON",
        "postal_code": "",
        "district": "Etobicoke York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=843",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 843,
    },
    {
        "name": "Gord and Irene Risk Community Recreation Centre",
        "address": "2650 Finch Ave W, Toronto, ON",
        "postal_code": "M9M 3A3",
        "district": "Etobicoke York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=642",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 642,
    },
    {
        "name": "Halbert Park",
        "address": "24 Rockwood Dr, Toronto, ON",
        "postal_code": "",
        "district": "Scarborough",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=768",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 768,
    },
    {
        "name": "Heron Park Community Recreation Centre",
        "address": "292 Manse Rd, Toronto, ON",
        "postal_code": "M1E 3V4",
        "district": "Scarborough",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=633",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 633,
    },
    {
        "name": "Irving W. Chapley Community Centre",
        "address": "205 Wilmington Ave, Toronto, ON",
        "postal_code": "M3H 6B3",
        "district": "North York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=664",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 664,
    },
    {
        "name": "Kidstown - Water Park",
        "address": "3159 Birchmount Rd, Toronto, ON",
        "postal_code": "",
        "district": "Scarborough",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=352",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 352,
    },
    {
        "name": "Knob Hill Park",
        "address": "625 Brimley Rd., Toronto, ON",
        "postal_code": "",
        "district": "Scarborough",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=690",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 690,
    },
    {
        "name": "Lambton - Kingsway Park",
        "address": "37 Marquis Ave, Toronto, ON",
        "postal_code": "",
        "district": "Etobicoke York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=847",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 847,
    },
    {
        "name": "Lawrence Heights Community Centre",
        "address": "5 Replin Rd, Toronto, ON",
        "postal_code": "M6A 2M8",
        "district": "North York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=675",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 675,
    },
    {
        "name": "Leaside Park",
        "address": "5 Leaside Park Dr, Toronto, ON",
        "postal_code": "",
        "district": "North York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=425",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 425,
    },
    {
        "name": "Ledbury Park",
        "address": "160 Ledbury St, Toronto, ON",
        "postal_code": "",
        "district": "North York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=678",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 678,
    },
    {
        "name": "Maryvale Park",
        "address": "5 Trestleside Grv, Toronto, ON",
        "postal_code": "",
        "district": "Scarborough",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=704",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 704,
    },
    {
        "name": "Mitchell Field Community Centre",
        "address": "89 Church Ave, Toronto, ON",
        "postal_code": "M2N 6C9",
        "district": "North York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=693",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 693,
    },
    {
        "name": "Monarch Park",
        "address": "115 Felstead Ave, Toronto, ON",
        "postal_code": "",
        "district": "Toronto and East York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=145",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 145,
    },
    {
        "name": "North Toronto Memorial Community Centre",
        "address": "200 Eglinton Ave W, Toronto, ON",
        "postal_code": "M4R 1A7",
        "district": "North York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=189",
        "is_indoor": False,
        "has_indoor": True,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 189,
    },
    {
        "name": "Northwood Community Centre",
        "address": "15 Clubhouse Crt, Toronto, ON",
        "postal_code": "M3L 2L7",
        "district": "Etobicoke York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=703",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 703,
    },
    {
        "name": "O'Connor Community Centre",
        "address": "1386 Victoria Park Ave, Toronto, ON",
        "postal_code": "M4A 2L8",
        "district": "Toronto and East York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=1093",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 1093,
    },
    {
        "name": "Oakdale Community Centre",
        "address": "350 Grandravine Dr, Toronto, ON",
        "postal_code": "M3J 1B3",
        "district": "Etobicoke York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=780",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 780,
    },
    {
        "name": "Park Lawn Park",
        "address": "330 Park Lawn Rd, Toronto, ON",
        "postal_code": "",
        "district": "Etobicoke York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=858",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 858,
    },
    {
        "name": "Parkway Forest Park",
        "address": "80 Parkway Forest Dr, Toronto, ON",
        "postal_code": "",
        "district": "North York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=718",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 718,
    },
    {
        "name": "Pine Point Park",
        "address": "4 Conan Rd, Toronto, ON",
        "postal_code": "",
        "district": "Etobicoke York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=859",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 859,
    },
    {
        "name": "Riverdale Park East",
        "address": "550 Broadview Ave, Toronto, ON",
        "postal_code": "",
        "district": "Toronto and East York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=343",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 343,
    },
    {
        "name": "Roding Community Centre",
        "address": "600 Roding St, Toronto, ON",
        "postal_code": "M3M 2A5",
        "district": "North York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=744",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 744,
    },
    {
        "name": "Rotary Peace Park",
        "address": "25 Eleventh St, Toronto, ON",
        "postal_code": "",
        "district": "Etobicoke York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=867",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 867,
    },
    {
        "name": "Silver Creek Park",
        "address": "44 Strathdee Dr., Toronto, ON",
        "postal_code": "",
        "district": "Etobicoke York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=877",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 877,
    },
    {
        "name": "Smithfield Park",
        "address": "173 Mount Olive Dr, Toronto, ON",
        "postal_code": "",
        "district": "Etobicoke York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=869",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 869,
    },
    {
        "name": "Smythe Park",
        "address": "175 Scarlett Rd, Toronto, ON",
        "postal_code": "",
        "district": "Etobicoke York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=504",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 504,
    },
    {
        "name": "Stan Wadlow Park",
        "address": "888 Cosburn Ave, Toronto, ON",
        "postal_code": "",
        "district": "Toronto and East York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=421",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 421,
    },
    {
        "name": "Stanley Park South - Toronto",
        "address": "700 Wellington St W, Toronto, ON",
        "postal_code": "",
        "district": "Toronto and East York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=2750",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 2750,
    },
    {
        "name": "Sunnyside Gus Ryder Outdoor Pool",
        "address": "1755 Lake Shore Blvd W, Toronto, ON",
        "postal_code": "",
        "district": "Toronto and East York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=433",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 433,
    },
    {
        "name": "Wedgewood Park - Etobicoke",
        "address": "15 Swan Ave, Toronto, ON",
        "postal_code": "",
        "district": "Etobicoke York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=773",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 773,
    },
    {
        "name": "West Deane Park",
        "address": "400 Martin Grove Road, Toronto, ON",
        "postal_code": "",
        "district": "Etobicoke York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=873",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 873,
    },
    {
        "name": "Westgrove Park",
        "address": "15 Redgrave Dr, Toronto, ON",
        "postal_code": "",
        "district": "Etobicoke York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=876",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 876,
    },
    {
        "name": "Westmount Park",
        "address": "22 Arcade Dr, Toronto, ON",
        "postal_code": "",
        "district": "Etobicoke York",
        "phone": "311",
        "website": "https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=2006",
        "is_indoor": False,
        "has_indoor": False,
        "has_outdoor": True,
        "has_lane_swim": True,
        "toronto_location_id": 2006,
    },
]


def resolve_pool_type_flags(facility_data: dict) -> tuple[bool, bool]:
    """Derive has_indoor/has_outdoor from explicit keys or legacy is_indoor."""
    has_indoor = facility_data.get("has_indoor")
    has_outdoor = facility_data.get("has_outdoor")
    if has_indoor is None and has_outdoor is None:
        is_indoor = facility_data.get("is_indoor", True)
        return is_indoor, not is_indoor
    if has_indoor is None:
        return not has_outdoor, has_outdoor
    if has_outdoor is None:
        return has_indoor, not has_indoor
    return has_indoor, has_outdoor


def get_all_indoor_pools():
    """Return list of all indoor pools."""
    return [p for p in TORONTO_INDOOR_POOLS if p.get("is_indoor", False)]


def get_all_swim_pools():
    """Return curated pools with lane swim (indoor and outdoor)."""
    return [p for p in TORONTO_INDOOR_POOLS if p.get("has_lane_swim", False)]


def get_lane_swim_pools():
    """Return list of pools with lane swim."""
    return [p for p in TORONTO_INDOOR_POOLS if p.get("has_lane_swim", False)]


def get_pools_by_district(district):
    """Return list of pools in a specific district."""
    return [p for p in TORONTO_INDOOR_POOLS if p.get("district") == district]


def get_pool_count():
    """Return count of pools."""
    return len(TORONTO_INDOOR_POOLS)

